export const products = [
  {
    id: 1,
    name: "Adidas Ultraboost",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: 120,
    offPrice: 120,
    discount: 0,
    images: [
      "https://images.sportsdirect.com/images/products/21190903_l.jpg",
      "https://images.sportsdirect.com/images/products/21190903_l_a1.jpg",
      "https://images.sportsdirect.com/images/products/21190903_l_a6.jpg",
    ],
    size: [37, 39, 42, 43],
  },
  {
    id: 2,
    name: "Asics Nimbus",
    description: [{ support: "گارانتی مادام العمر" }, { support: "اورجینال" }],
    price: 110,
    offPrice: 100,
    discount: 8,
    images: [
      "https://images.sportsdirect.com/images/products/21211018_l.jpg",
      "https://images.sportsdirect.com/images/products/21211018_l_a2.jpg",
      "https://images.sportsdirect.com/images/products/21211018_l_a3.jpg",
    ],
    size: [39, 40, 41, 42, 43],
  },
  {
    id: 3,
    name: "Nike Air Zoom",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 109,
    offPrice: 99,
    discount: 10,
    images: [
      "https://images.sportsdirect.com/images/products/21127827_l.jpg",
      "https://images.sportsdirect.com/images/products/21127827_l_a6.jpg",
      "https://images.sportsdirect.com/images/products/21127827_l_a5.jpg",
    ],
    size: [37, 38, 41, 42, 44],
  },
  {
    id: 4,
    name: "New Balance FF",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 160,
    offPrice: 130,
    discount: 15,
    images: [
      "https://images.sportsdirect.com/images/products/21604112_l.jpg",
      "https://images.sportsdirect.com/images/products/21604112_l_a2.jpg",
      "https://images.sportsdirect.com/images/products/21604112_l_a1.jpg",
    ],
    size: [38, 39, 40, 43, 44],
  },
  {
    id: 5,
    name: "Nike Pegasus",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 150,
    offPrice: 150,
    discount: 0,
    images: [
      "https://images.sportsdirect.com/images/products/21611524_l.jpg",
      "https://images.sportsdirect.com/images/products/21611524_l_a5.jpg",
      "https://images.sportsdirect.com/images/products/21611524_l_a6.jpg",
    ],
    size: [39, 40, 41, 42],
  },
  {
    id: 6,
    name: "New Balance Fresh",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 135,
    offPrice: 125,
    discount: 13,
    images: [
      "https://images.sportsdirect.com/images/products/21464612_l.jpg",
      "https://images.sportsdirect.com/images/products/21464612_l_a2.jpg",
      "https://images.sportsdirect.com/images/products/21464612_l_a5.jpg",
    ],
    size: [37, 39, 40, 42, 44],
  },
];
export const sizeOptions = [
  { value: 35, label: "35" },
  { value: 36, label: "36" },
  { value: 37, label: "37" },
  { value: 38, label: "38" },
  { value: 39, label: "39" },
  { value: 40, label: "40" },
  { value: 41, label: "41" },
  { value: 42, label: "42" },
  { value: 43, label: "43" },
  { value: 44, label: "44" },
  { value: 45, label: "45" },
  { value: 46, label: "46" },
  { value: 47, label: "47" },
  { value: 48, label: "48" },
  { value: 49, label: "49" },
];
// export const users = [
//   {
//     name: "Saheb mohamadi",
//     email: "saheb.ex@gmail.com",
//     password: bcrypt.hashSync("12345", 8),
//     phoneNumber: "09180000000",
//     isAdmin: true,
//   },
//   {
//     name: "John",
//     email: "user@example.com",
//     password: bcrypt.hashSync("1234", 8),
//     isAdmin: false,
//     phoneNumber: "09181230000",
//   },
// ];
